name: app1
host: project-local-egor.local
image:
  repository: narland/java
  tag: 20260114141240-f90a9755caa1577b83afe6858d397fcc0eb2fe18
port: 8080
replicas: 1

ingress:
  enabled: true
  className: traefik
