name: app2
host: project-local-egor2.local
image:
  repository: narland/java
  tag: 20260116073303-941b538439304c9314b970e839cea990acdc0649
port: 8080
replicas: 1
ingress:
  enabled: true
  className: traefik
